[2025-09-22T14:02:06.108+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_fact_booking.run_load_fact_booking manual__2025-09-22T14:02:04.835694+00:00 [queued]>
[2025-09-22T14:02:06.120+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_fact_booking.run_load_fact_booking manual__2025-09-22T14:02:04.835694+00:00 [queued]>
[2025-09-22T14:02:06.120+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-09-22T14:02:06.142+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_load_fact_booking> on 2025-09-22 14:02:04.835694+00:00
[2025-09-22T14:02:06.157+0000] {standard_task_runner.py:57} INFO - Started process 196 to run task
[2025-09-22T14:02:06.159+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_fact_booking', 'run_load_fact_booking', 'manual__2025-09-22T14:02:04.835694+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/load_fact_booking_dag.py', '--cfg-path', '/tmp/tmp1clpx_l3']
[2025-09-22T14:02:06.166+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask run_load_fact_booking
[2025-09-22T14:02:06.277+0000] {task_command.py:416} INFO - Running <TaskInstance: load_fact_booking.run_load_fact_booking manual__2025-09-22T14:02:04.835694+00:00 [running]> on host 55246324e4c7
[2025-09-22T14:02:06.426+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_fact_booking' AIRFLOW_CTX_TASK_ID='run_load_fact_booking' AIRFLOW_CTX_EXECUTION_DATE='2025-09-22T14:02:04.835694+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-22T14:02:04.835694+00:00'
[2025-09-22T14:02:06.427+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-22T14:02:06.429+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash -c "/opt/***/jobs/Load_Fact_Booking/Load_Fact_Booking_run.sh"']
[2025-09-22T14:02:06.444+0000] {subprocess.py:86} INFO - Output:
[2025-09-22T14:02:06.450+0000] {subprocess.py:93} INFO - bash: line 1: /opt/***/jobs/Load_Fact_Booking/Load_Fact_Booking_run.sh: Permission denied
[2025-09-22T14:02:06.451+0000] {subprocess.py:97} INFO - Command exited with return code 126
[2025-09-22T14:02:06.465+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-09-22T14:02:06.470+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=load_fact_booking, task_id=run_load_fact_booking, execution_date=20250922T140204, start_date=20250922T140206, end_date=20250922T140206
[2025-09-22T14:02:06.488+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task run_load_fact_booking (Bash command failed. The command returned a non-zero exit code 126.; 196)
[2025-09-22T14:02:06.499+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-22T14:02:06.527+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
