[2025-09-22T14:03:07.706+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_fact_booking.run_load_fact_booking manual__2025-09-22T14:02:04.835694+00:00 [queued]>
[2025-09-22T14:03:07.721+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_fact_booking.run_load_fact_booking manual__2025-09-22T14:02:04.835694+00:00 [queued]>
[2025-09-22T14:03:07.722+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-09-22T14:03:07.752+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_load_fact_booking> on 2025-09-22 14:02:04.835694+00:00
[2025-09-22T14:03:07.762+0000] {standard_task_runner.py:57} INFO - Started process 209 to run task
[2025-09-22T14:03:07.771+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_fact_booking', 'run_load_fact_booking', 'manual__2025-09-22T14:02:04.835694+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/load_fact_booking_dag.py', '--cfg-path', '/tmp/tmpsol318ni']
[2025-09-22T14:03:07.777+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask run_load_fact_booking
[2025-09-22T14:03:07.887+0000] {task_command.py:416} INFO - Running <TaskInstance: load_fact_booking.run_load_fact_booking manual__2025-09-22T14:02:04.835694+00:00 [running]> on host 55246324e4c7
[2025-09-22T14:03:08.121+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_fact_booking' AIRFLOW_CTX_TASK_ID='run_load_fact_booking' AIRFLOW_CTX_EXECUTION_DATE='2025-09-22T14:02:04.835694+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-22T14:02:04.835694+00:00'
[2025-09-22T14:03:08.124+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-22T14:03:08.128+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'bash -c "/opt/***/jobs/Load_Fact_Booking/Load_Fact_Booking_run.sh"']
[2025-09-22T14:03:08.152+0000] {subprocess.py:86} INFO - Output:
[2025-09-22T14:03:08.160+0000] {subprocess.py:93} INFO - bash: line 1: /opt/***/jobs/Load_Fact_Booking/Load_Fact_Booking_run.sh: Permission denied
[2025-09-22T14:03:08.161+0000] {subprocess.py:97} INFO - Command exited with return code 126
[2025-09-22T14:03:08.179+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 126.
[2025-09-22T14:03:08.185+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=load_fact_booking, task_id=run_load_fact_booking, execution_date=20250922T140204, start_date=20250922T140307, end_date=20250922T140308
[2025-09-22T14:03:08.210+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task run_load_fact_booking (Bash command failed. The command returned a non-zero exit code 126.; 209)
[2025-09-22T14:03:08.266+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-22T14:03:08.294+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
